/**
 * File conversion utilities for Arduino compilation
 * Converts EditorFile format to Arduino FileMap format
 */

import { ARDUINO_FILE_EXTENSIONS, FileMap } from '@renderer/services/arduino/types'

/**
 * Editor file interface (based on your redux file structure)
 */
export interface EditorFile {
  id: string
  name: string
  content: string
  path?: string
  type?: 'file' | 'folder'
  children?: EditorFile[]
}

/**
 * Convert EditorFile array to Arduino FileMap
 * Filters for Arduino-compatible files and creates relative paths
 */
export function convertToFileMap(files: EditorFile[]): FileMap {
  const fileMap: FileMap = {}

  function processFile(file: EditorFile, basePath: string = ''): void {
    if (file.type === 'folder' && file.children) {
      // Process folder contents
      const folderPath = basePath ? `${basePath}/${file.name}` : file.name
      file.children.forEach((child) => processFile(child, folderPath))
    } else if (file.type === 'file' || !file.type) {
      // Check if file is Arduino-compatible
      if (isArduinoFile(file.name)) {
        const relativePath = basePath ? `${basePath}/${file.name}` : file.name
        fileMap[relativePath] = file.content || ''
      }
    }
  }

  files.forEach((file) => processFile(file))
  return fileMap
}

/**
 * Convert single EditorFile to FileMap (for single file compilation)
 */
export function convertSingleFileToFileMap(file: EditorFile): FileMap {
  if (!isArduinoFile(file.name)) {
    throw new Error(`File ${file.name} is not an Arduino-compatible file`)
  }

  return {
    [file.name]: file.content || ''
  }
}

/**
 * Get Arduino sketch files from workspace
 * Finds main .ino file and related files
 */
export function getSketchFiles(files: EditorFile[], mainSketch?: string): FileMap {
  const fileMap = convertToFileMap(files)

  // Find main sketch file
  const inoFiles = Object.keys(fileMap).filter((path) => path.endsWith('.ino'))

  if (inoFiles.length === 0) {
    throw new Error('No Arduino sketch (.ino) files found')
  }

  // Use specified main sketch or first .ino file found
  const mainFile = mainSketch || inoFiles[0]

  if (!fileMap[mainFile]) {
    throw new Error(`Main sketch file ${mainFile} not found`)
  }

  // Ensure main sketch has proper content
  if (!fileMap[mainFile].trim()) {
    throw new Error(`Main sketch file ${mainFile} is empty`)
  }

  return fileMap
}

/**
 * Check if file is Arduino-compatible
 */
export function isArduinoFile(filename: string): boolean {
  return ARDUINO_FILE_EXTENSIONS.some((ext) => filename.toLowerCase().endsWith(ext))
}

/**
 * Get main sketch name from FileMap
 */
export function getMainSketchName(fileMap: FileMap): string {
  const inoFiles = Object.keys(fileMap).filter((path) => path.endsWith('.ino'))

  if (inoFiles.length === 0) {
    throw new Error('No .ino files found in FileMap')
  }

  // Return the first .ino file or the one that matches the directory name
  return inoFiles[0]
}

/**
 * Validate FileMap for Arduino compilation
 */
export function validateFileMap(fileMap: FileMap): {
  isValid: boolean
  errors: string[]
  warnings: string[]
} {
  const errors: string[] = []
  const warnings: string[] = []

  // Check for .ino files
  const inoFiles = Object.keys(fileMap).filter((path) => path.endsWith('.ino'))
  if (inoFiles.length === 0) {
    errors.push('No Arduino sketch (.ino) files found')
  } else if (inoFiles.length > 1) {
    warnings.push(
      `Multiple .ino files found: ${inoFiles.join(', ')}. Using ${inoFiles[0]} as main sketch.`
    )
  }

  // Check for empty files
  Object.entries(fileMap).forEach(([path, content]) => {
    if (!content.trim()) {
      warnings.push(`File ${path} is empty`)
    }
  })

  // Check for setup() and loop() functions in main sketch
  if (inoFiles.length > 0) {
    const mainContent = fileMap[inoFiles[0]]
    if (!mainContent.includes('setup(') && !mainContent.includes('setup ')) {
      warnings.push('Main sketch may be missing setup() function')
    }
    if (!mainContent.includes('loop(') && !mainContent.includes('loop ')) {
      warnings.push('Main sketch may be missing loop() function')
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings
  }
}

/**
 * Create default Arduino sketch content
 */
export function createDefaultSketch(sketchName: string = 'sketch'): FileMap {
  const content = `// ${sketchName}
// Generated by tinyStudio

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
}

void loop() {
  // put your main code here, to run repeatedly:
  
}
`

  return {
    [`${sketchName}.ino`]: content
  }
}

/**
 * Merge multiple FileMaps (useful for including libraries)
 */
export function mergeFileMaps(...fileMaps: FileMap[]): FileMap {
  const merged: FileMap = {}

  fileMaps.forEach((fileMap) => {
    Object.entries(fileMap).forEach(([path, content]) => {
      if (merged[path] && merged[path] !== content) {
        console.warn(`File conflict: ${path} has different content in multiple FileMaps`)
      }
      merged[path] = content
    })
  })

  return merged
}

/**
 * Filter FileMap to only include specific file types
 */
export function filterFilesByExtension(fileMap: FileMap, extensions: string[]): FileMap {
  const filtered: FileMap = {}

  Object.entries(fileMap).forEach(([path, content]) => {
    if (extensions.some((ext) => path.toLowerCase().endsWith(ext.toLowerCase()))) {
      filtered[path] = content
    }
  })

  return filtered
}

/**
 * Get file statistics from FileMap
 */
export function getFileMapStats(fileMap: FileMap): {
  totalFiles: number
  totalSize: number
  fileTypes: { [extension: string]: number }
  largestFile: { path: string; size: number } | null
} {
  const stats = {
    totalFiles: 0,
    totalSize: 0,
    fileTypes: {} as { [extension: string]: number },
    largestFile: null as { path: string; size: number } | null
  }

  Object.entries(fileMap).forEach(([path, content]) => {
    const size = new Blob([content]).size
    const extension = path.split('.').pop()?.toLowerCase() || 'unknown'

    stats.totalFiles++
    stats.totalSize += size
    stats.fileTypes[extension] = (stats.fileTypes[extension] || 0) + 1

    if (!stats.largestFile || size > stats.largestFile.size) {
      stats.largestFile = { path, size }
    }
  })

  return stats
}
