/**
 * partsLibrary — the source of truth for circuit parts.
 *
 * Parts come from two places:
 *  1. Built-in tinyStudio boards (the tiny* family), whose Fritzing-style
 *     breadboard art lives in assets/tinyboards/ and is generated by
 *     `scripts/gen-tinyboards.py`.
 *  2. The Fritzing-imported library under assets/parts/, generated by
 *     `scripts/fritzing-import.mjs`. Each part is its own JSON file grouped by
 *     family and lazy-loaded on demand (so opening one family doesn't pull the
 *     SVGs for the whole catalogue).
 *
 * Both share one schema. Pin coordinates are pixels @ 96 DPI relative to the
 * part's top-left — the same space Wokwi uses — so a part drops straight into
 * diagram.json. A part can carry a `breadboard` and/or `schematic` view; pin
 * NAMES are stable across views, which is what lets connections survive a view
 * switch and stay valid Wokwi data.
 */

import { compareCategories, resolveNaming } from '../circuit/parts/naming'
import { invalidateSymbol } from '../circuit/parts/symbols'
import manifestJson from '../assets/parts/index.json'
import tinycoreArt from '../assets/tinyboards/tinycore.svg?raw'
import tinyglowArt from '../assets/tinyboards/tinyglow.svg?raw'
import tinyprotoArt from '../assets/tinyboards/tinyproto.svg?raw'
import tinysniffArt from '../assets/tinyboards/tinysniff.svg?raw'
import tinyspeakArt from '../assets/tinyboards/tinyspeak.svg?raw'
import tinydisplayArt from '../assets/tinyboards/tinydisplay.svg?raw'

export type ViewKind = 'breadboard' | 'schematic'

export interface PartView {
  svg: string
  w: number
  h: number
  pins: Record<string, [number, number]>
  /** pin names with a bendable rubber-band leg in this view (Fritzing
   * legId — LED/resistor class parts). Breadboard view only in practice. */
  legs?: string[]
}

export interface PartDef {
  type: string
  /** Display name (human-readable — see circuit/parts/naming). */
  label: string
  /** Display category — the group this part sits in, in the components rail. */
  family?: string
  /**
   * Keyword string used for SPICE emitter + refdes matching, kept separate
   * from the display category so renaming a category can never change how a
   * part simulates. Falls back to `family` when absent.
   */
  simFamily?: string
  /** Explicit refdes prefix (R, C, D, Q…) when the part knows better. */
  prefix?: string
  sub?: string
  accent?: string
  builtin?: boolean
  icon?: string
  views: Partial<Record<ViewKind, PartView>>
}

export interface PartMeta {
  type: string
  label: string
  /** Display category (see circuit/parts/naming). */
  family: string
  /** Keyword string for sim/refdes matching — never the display category. */
  simFamily?: string
  prefix?: string
  familySlug?: string
  views: ViewKind[]
  pins: number
  icon?: string
  file?: string
  builtin?: boolean
}

// ── built-in tinyStudio boards ───────────────────────────────────────────────
// Fritzing-style breadboard art for the tinyBoard family, drawn to the real
// hardware: a 1.9in (48.26 mm) regular octagon on a 0.1in grid, with component
// placement, silkscreen and colours measured off the product photos.
//
// Every tinyBoard carries the SAME 25-pin stack connector — 8 pins up the left
// (ANALOG), 8 up the right (DIGITAL), 9 across the bottom (SERIAL + power) —
// which is what lets them stack, so one pin map serves the whole family.
// tinyProto adds its 183-hole prototyping cross on the same 0.1in lattice.
//
// The art is generated: `python3 scripts/gen-tinyboards.py` rewrites
// assets/tinyboards/*.svg. Edit the generator, not the SVGs.

/** 1.9in @ 96 DPI — the pixel box the SVG's 136.8-unit viewBox maps onto. */
const BOARD_PX = 182.4

/** The shared 25-pin tinyBoard stack connector, px @ 96 DPI from top-left. */
const STACK_PINS: Record<string, [number, number]> = {
  // left header — ANALOG, top to bottom
  GND: [7.2, 57.6],
  '3V3': [7.2, 67.2],
  A5: [7.2, 76.8],
  A4: [7.2, 86.4],
  A3: [7.2, 96.0],
  A2: [7.2, 105.6],
  A1: [7.2, 115.2],
  A0: [7.2, 124.8],
  // right header — DIGITAL, top to bottom
  D8: [175.2, 57.6],
  D9: [175.2, 67.2],
  D10: [175.2, 76.8],
  D11: [175.2, 86.4],
  D12: [175.2, 96.0],
  D13: [175.2, 105.6],
  '3V3.2': [175.2, 115.2],
  'GND.2': [175.2, 124.8],
  // bottom header — SERIAL, left to right
  SCK: [52.8, 170.4],
  MO: [62.4, 170.4],
  MI: [72.0, 170.4],
  RX: [81.6, 170.4],
  TX: [91.2, 170.4],
  SDA: [100.8, 170.4],
  SCL: [110.4, 170.4],
  PWR: [120.0, 170.4],
  'GND.3': [129.6, 170.4]
}

/**
 * tinyProto's prototyping field: a cross of plated holes on the same 0.1in
 * lattice as the headers — 15 columns (A..O) across the 8 header rows, plus the
 * 9 header columns down all 15 rows. Named `<column>.<row>` so they can never
 * collide with a pin name like A0 or D8.
 */
const PROTO_HOLES: Record<string, [number, number]> = {
  'A.5': [24.0, 57.6],
  'A.6': [24.0, 67.2],
  'A.7': [24.0, 76.8],
  'A.8': [24.0, 86.4],
  'A.9': [24.0, 96.0],
  'A.10': [24.0, 105.6],
  'A.11': [24.0, 115.2],
  'A.12': [24.0, 124.8],
  'B.5': [33.6, 57.6],
  'B.6': [33.6, 67.2],
  'B.7': [33.6, 76.8],
  'B.8': [33.6, 86.4],
  'B.9': [33.6, 96.0],
  'B.10': [33.6, 105.6],
  'B.11': [33.6, 115.2],
  'B.12': [33.6, 124.8],
  'C.5': [43.2, 57.6],
  'C.6': [43.2, 67.2],
  'C.7': [43.2, 76.8],
  'C.8': [43.2, 86.4],
  'C.9': [43.2, 96.0],
  'C.10': [43.2, 105.6],
  'C.11': [43.2, 115.2],
  'C.12': [43.2, 124.8],
  'D.1': [52.8, 19.2],
  'D.2': [52.8, 28.8],
  'D.3': [52.8, 38.4],
  'D.4': [52.8, 48.0],
  'D.5': [52.8, 57.6],
  'D.6': [52.8, 67.2],
  'D.7': [52.8, 76.8],
  'D.8': [52.8, 86.4],
  'D.9': [52.8, 96.0],
  'D.10': [52.8, 105.6],
  'D.11': [52.8, 115.2],
  'D.12': [52.8, 124.8],
  'D.13': [52.8, 134.4],
  'D.14': [52.8, 144.0],
  'D.15': [52.8, 153.6],
  'E.1': [62.4, 19.2],
  'E.2': [62.4, 28.8],
  'E.3': [62.4, 38.4],
  'E.4': [62.4, 48.0],
  'E.5': [62.4, 57.6],
  'E.6': [62.4, 67.2],
  'E.7': [62.4, 76.8],
  'E.8': [62.4, 86.4],
  'E.9': [62.4, 96.0],
  'E.10': [62.4, 105.6],
  'E.11': [62.4, 115.2],
  'E.12': [62.4, 124.8],
  'E.13': [62.4, 134.4],
  'E.14': [62.4, 144.0],
  'E.15': [62.4, 153.6],
  'F.1': [72.0, 19.2],
  'F.2': [72.0, 28.8],
  'F.3': [72.0, 38.4],
  'F.4': [72.0, 48.0],
  'F.5': [72.0, 57.6],
  'F.6': [72.0, 67.2],
  'F.7': [72.0, 76.8],
  'F.8': [72.0, 86.4],
  'F.9': [72.0, 96.0],
  'F.10': [72.0, 105.6],
  'F.11': [72.0, 115.2],
  'F.12': [72.0, 124.8],
  'F.13': [72.0, 134.4],
  'F.14': [72.0, 144.0],
  'F.15': [72.0, 153.6],
  'G.1': [81.6, 19.2],
  'G.2': [81.6, 28.8],
  'G.3': [81.6, 38.4],
  'G.4': [81.6, 48.0],
  'G.5': [81.6, 57.6],
  'G.6': [81.6, 67.2],
  'G.7': [81.6, 76.8],
  'G.8': [81.6, 86.4],
  'G.9': [81.6, 96.0],
  'G.10': [81.6, 105.6],
  'G.11': [81.6, 115.2],
  'G.12': [81.6, 124.8],
  'G.13': [81.6, 134.4],
  'G.14': [81.6, 144.0],
  'G.15': [81.6, 153.6],
  'H.1': [91.2, 19.2],
  'H.2': [91.2, 28.8],
  'H.3': [91.2, 38.4],
  'H.4': [91.2, 48.0],
  'H.5': [91.2, 57.6],
  'H.6': [91.2, 67.2],
  'H.7': [91.2, 76.8],
  'H.8': [91.2, 86.4],
  'H.9': [91.2, 96.0],
  'H.10': [91.2, 105.6],
  'H.11': [91.2, 115.2],
  'H.12': [91.2, 124.8],
  'H.13': [91.2, 134.4],
  'H.14': [91.2, 144.0],
  'H.15': [91.2, 153.6],
  'I.1': [100.8, 19.2],
  'I.2': [100.8, 28.8],
  'I.3': [100.8, 38.4],
  'I.4': [100.8, 48.0],
  'I.5': [100.8, 57.6],
  'I.6': [100.8, 67.2],
  'I.7': [100.8, 76.8],
  'I.8': [100.8, 86.4],
  'I.9': [100.8, 96.0],
  'I.10': [100.8, 105.6],
  'I.11': [100.8, 115.2],
  'I.12': [100.8, 124.8],
  'I.13': [100.8, 134.4],
  'I.14': [100.8, 144.0],
  'I.15': [100.8, 153.6],
  'J.1': [110.4, 19.2],
  'J.2': [110.4, 28.8],
  'J.3': [110.4, 38.4],
  'J.4': [110.4, 48.0],
  'J.5': [110.4, 57.6],
  'J.6': [110.4, 67.2],
  'J.7': [110.4, 76.8],
  'J.8': [110.4, 86.4],
  'J.9': [110.4, 96.0],
  'J.10': [110.4, 105.6],
  'J.11': [110.4, 115.2],
  'J.12': [110.4, 124.8],
  'J.13': [110.4, 134.4],
  'J.14': [110.4, 144.0],
  'J.15': [110.4, 153.6],
  'K.1': [120.0, 19.2],
  'K.2': [120.0, 28.8],
  'K.3': [120.0, 38.4],
  'K.4': [120.0, 48.0],
  'K.5': [120.0, 57.6],
  'K.6': [120.0, 67.2],
  'K.7': [120.0, 76.8],
  'K.8': [120.0, 86.4],
  'K.9': [120.0, 96.0],
  'K.10': [120.0, 105.6],
  'K.11': [120.0, 115.2],
  'K.12': [120.0, 124.8],
  'K.13': [120.0, 134.4],
  'K.14': [120.0, 144.0],
  'K.15': [120.0, 153.6],
  'L.1': [129.6, 19.2],
  'L.2': [129.6, 28.8],
  'L.3': [129.6, 38.4],
  'L.4': [129.6, 48.0],
  'L.5': [129.6, 57.6],
  'L.6': [129.6, 67.2],
  'L.7': [129.6, 76.8],
  'L.8': [129.6, 86.4],
  'L.9': [129.6, 96.0],
  'L.10': [129.6, 105.6],
  'L.11': [129.6, 115.2],
  'L.12': [129.6, 124.8],
  'L.13': [129.6, 134.4],
  'L.14': [129.6, 144.0],
  'L.15': [129.6, 153.6],
  'M.5': [139.2, 57.6],
  'M.6': [139.2, 67.2],
  'M.7': [139.2, 76.8],
  'M.8': [139.2, 86.4],
  'M.9': [139.2, 96.0],
  'M.10': [139.2, 105.6],
  'M.11': [139.2, 115.2],
  'M.12': [139.2, 124.8],
  'N.5': [148.8, 57.6],
  'N.6': [148.8, 67.2],
  'N.7': [148.8, 76.8],
  'N.8': [148.8, 86.4],
  'N.9': [148.8, 96.0],
  'N.10': [148.8, 105.6],
  'N.11': [148.8, 115.2],
  'N.12': [148.8, 124.8],
  'O.5': [158.4, 57.6],
  'O.6': [158.4, 67.2],
  'O.7': [158.4, 76.8],
  'O.8': [158.4, 86.4],
  'O.9': [158.4, 96.0],
  'O.10': [158.4, 105.6],
  'O.11': [158.4, 115.2],
  'O.12': [158.4, 124.8]
}

/**
 * The five silkscreened buses on tinyProto (the ringed hole groups beside the
 * power pins). Every other hole is its own electrical island, exactly like the
 * real board — no breadboard-style shared rows.
 */
export const TINYPROTO_BUSES: string[][] = [
  ['A.5', 'B.5', 'C.5', 'D.2', 'D.3', 'D.4'],
  ['A.6', 'B.6', 'C.6'],
  ['M.11', 'N.11', 'O.11'],
  ['M.12', 'N.12', 'O.12', 'L.13', 'L.14', 'L.15'],
  ['K.13', 'K.14', 'K.15']
]

/** Regular octagon inset 1px in a 48px box — the family silhouette. */
const OCTAGON = '14.5,1 33.5,1 47,14.5 47,33.5 33.5,47 14.5,47 1,33.5 1,14.5'

/** Palette glyph: the board outline in its own soldermask colour. */
function boardIcon(short: string, mask: string, accent: string, ink: string): string {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">` +
    `<polygon points="${OCTAGON}" fill="${mask}" stroke="${accent}" stroke-width="1.6"/>` +
    `<text x="24" y="27" font-family="sans-serif" font-size="8" font-style="italic" ` +
    `fill="${ink}" text-anchor="middle">${short}</text></svg>`
  )
}

function board(
  type: string,
  label: string,
  art: string,
  opts: { sub: string; mask: string; accent: string; ink?: string; protoHoles?: boolean }
): PartDef {
  return {
    type,
    label,
    family: 'tinyStudio',
    sub: opts.sub,
    accent: opts.accent,
    builtin: true,
    icon: boardIcon(label.slice(4), opts.mask, opts.accent, opts.ink || '#ffffff'),
    views: {
      breadboard: {
        svg: art,
        w: BOARD_PX,
        h: BOARD_PX,
        pins: opts.protoHoles ? { ...STACK_PINS, ...PROTO_HOLES } : { ...STACK_PINS }
      }
    }
  }
}

const BUILTIN_PARTS: PartDef[] = [
  board('tinycore', 'tinyCore', tinycoreArt, {
    sub: 'ESP32-S3',
    mask: '#1b2422',
    accent: 'var(--cyan)'
  }),
  board('tinyglow', 'tinyGlow', tinyglowArt, {
    sub: '3-channel LED driver',
    mask: '#1d4bad',
    accent: 'var(--pink)'
  }),
  board('tinyproto', 'tinyProto', tinyprotoArt, {
    sub: 'Prototyping / breakout',
    mask: '#0a9950',
    accent: '#3fc47a',
    protoHoles: true
  }),
  board('tinysniff', 'tinySniff', tinysniffArt, {
    sub: 'MEMS gas sensor array',
    mask: '#efb812',
    accent: '#e0a90d',
    ink: '#2a2410'
  }),
  board('tinyspeak', 'tinySpeak', tinyspeakArt, {
    sub: 'Microphone + speaker',
    mask: '#e8382c',
    accent: '#f0655c'
  }),
  board('tinydisplay', 'tinyDisplay', tinydisplayArt, {
    sub: 'Round LCD module',
    mask: '#0e7d6c',
    accent: '#2fbfa6'
  })
]

// ── registry + lazy loading ──────────────────────────────────────────────────

// Lazy per-part loading. Each part is a flat file under assets/parts/ (Vite's
// dynamic-import variables only support a single path segment, so the family
// grouping lives in the manifest, not in directories). The ".json" extension
// stays in the static part of the template so Vite can analyze the glob.
/**
 * Naming pass (see circuit/parts/naming): every part that enters the registry
 * — built-in, lazily loaded, dropped .fzpz, pack install, user-authored —
 * goes through here, so a part's display name and category are decided in
 * exactly one place. The part file's own label/family survive as the
 * sim-matching keywords in `simFamily`.
 */
export function applyNaming<T extends PartDef>(def: T): T {
  const n = resolveNaming(def.type, def.label, def.simFamily ?? def.family)
  return {
    ...def,
    label: n.label,
    family: n.category,
    simFamily: n.sim,
    prefix: def.prefix ?? n.prefix
  }
}

function applyNamingMeta(meta: PartMeta): PartMeta {
  const n = resolveNaming(meta.type, meta.label, meta.simFamily ?? meta.family)
  return {
    ...meta,
    label: n.label,
    family: n.category,
    simFamily: n.sim,
    prefix: meta.prefix ?? n.prefix
  }
}

const rawManifest = ((manifestJson as { parts?: PartMeta[] }).parts || []).map(applyNamingMeta)
const loaderByType: Record<string, () => Promise<{ default: PartDef }>> = {}
for (const m of (manifestJson as { parts?: PartMeta[] }).parts || []) {
  if (!m.file) continue
  const rel = m.file.replace(/\.json$/, '')
  loaderByType[m.type] = () => import(`../assets/parts/${rel}.json`)
}

const cache: Record<string, PartDef> = {}
for (const d of BUILTIN_PARTS) cache[d.type] = applyNaming(d)

const builtinMeta: PartMeta[] = BUILTIN_PARTS.map((d) =>
  applyNamingMeta({
    type: d.type,
    label: d.label,
    family: d.family || 'tinyStudio',
    views: Object.keys(d.views) as ViewKind[],
    pins: Object.keys(Object.values(d.views)[0]?.pins || {}).length,
    icon: d.icon || Object.values(d.views)[0]?.svg,
    builtin: true
  })
)

/** Palette metadata: built-ins first, then the Fritzing catalogue. */
export const PART_MANIFEST: PartMeta[] = [...builtinMeta, ...rawManifest]

/**
 * Manifest grouped by display category for the components rail, in the
 * curated category order (circuit/parts/naming CATEGORY_ORDER), parts sorted
 * by name inside each group.
 */
export function partsByFamily(): { family: string; parts: PartMeta[] }[] {
  const groups = new Map<string, PartMeta[]>()
  for (const p of PART_MANIFEST) {
    if (!groups.has(p.family)) groups.set(p.family, [])
    groups.get(p.family)!.push(p)
  }
  return Array.from(groups, ([family, parts]) => ({
    family,
    parts: [...parts].sort((a, b) => a.label.localeCompare(b.label))
  })).sort((a, b) => compareCategories(a.family, b.family))
}

/** Synchronous lookup — only returns parts already loaded (built-ins + cached). */
export function getPart(type: string): PartDef | undefined {
  return cache[type]
}

/** Load a part definition (from cache if present, else its JSON file). */
export async function loadPart(type: string): Promise<PartDef | undefined> {
  if (cache[type]) return cache[type]
  const loader = loaderByType[type]
  if (!loader) return undefined
  const mod = await loader()
  cache[type] = applyNaming(mod.default)
  return cache[type]
}

/** Ensure every given type is loaded; resolves once the cache is populated. */
export async function ensureParts(types: Iterable<string>): Promise<void> {
  await Promise.all(Array.from(new Set(types)).map((t) => loadPart(t).catch(() => undefined)))
}

/** Register a user-authored part (from the Parts Editor) into the live registry. */
export function registerPart(raw: PartDef): void {
  const def = applyNaming(raw)
  cache[def.type] = def
  // a re-registered part (Parts Editor save, pack update) may have new art
  invalidateSymbol(def.type)
  const existing = PART_MANIFEST.findIndex((m) => m.type === def.type)
  const meta: PartMeta = {
    type: def.type,
    label: def.label,
    family: def.family || 'Custom',
    simFamily: def.simFamily,
    prefix: def.prefix,
    views: Object.keys(def.views) as ViewKind[],
    pins: Object.keys(Object.values(def.views)[0]?.pins || {}).length,
    icon: def.icon || Object.values(def.views)[0]?.svg,
    builtin: def.builtin
  }
  if (existing >= 0) PART_MANIFEST[existing] = meta
  else PART_MANIFEST.push(meta)
}

/** Pick the best available view for a part, preferring the requested one. */
export function viewFor(def: PartDef, view: ViewKind): PartView | undefined {
  return def.views[view] || def.views.breadboard || def.views.schematic
}
