/**
 * partsLibrary — the source of truth for circuit parts.
 *
 * Parts come from two places:
 *  1. Built-in tinyStudio boards (the tiny* family) authored inline below.
 *  2. The Fritzing-imported library under assets/parts/, generated by
 *     `scripts/fritzing-import.mjs`. Each part is its own JSON file grouped by
 *     family and lazy-loaded on demand (so opening one family doesn't pull the
 *     SVGs for the whole catalogue).
 *
 * Both share one schema. Pin coordinates are pixels @ 96 DPI relative to the
 * part's top-left — the same space Wokwi uses — so a part drops straight into
 * diagram.json. A part can carry a `breadboard` and/or `schematic` view; pin
 * NAMES are stable across views, which is what lets connections survive a view
 * switch and stay valid Wokwi data.
 */

import manifestJson from '../assets/parts/index.json'

export type ViewKind = 'breadboard' | 'schematic'

export interface PartView {
  svg: string
  w: number
  h: number
  pins: Record<string, [number, number]>
}

export interface PartDef {
  type: string
  label: string
  family?: string
  sub?: string
  accent?: string
  builtin?: boolean
  icon?: string
  views: Partial<Record<ViewKind, PartView>>
}

export interface PartMeta {
  type: string
  label: string
  family: string
  familySlug?: string
  views: ViewKind[]
  pins: number
  icon?: string
  file?: string
  builtin?: boolean
}

// ── built-in tinyStudio boards ───────────────────────────────────────────────

function boardSvg(
  label: string,
  sub: string | undefined,
  w: number,
  h: number,
  accent: string
): string {
  const cy = sub ? h / 2 - 6 : h / 2
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">
    <defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#172246"/><stop offset="1" stop-color="#0b1330"/>
    </linearGradient></defs>
    <rect x="1" y="1" width="${w - 2}" height="${h - 2}" rx="12" fill="url(#g)" stroke="${accent}" stroke-width="1.5"/>
    <text x="${w / 2}" y="${cy}" fill="#e9edff" font-family="sans-serif" font-size="15" font-weight="600" text-anchor="middle" dominant-baseline="middle">${label}</text>
    ${sub ? `<text x="${w / 2}" y="${h / 2 + 14}" fill="#7b86b8" font-family="sans-serif" font-size="11" text-anchor="middle" dominant-baseline="middle">${sub}</text>` : ''}
  </svg>`
}

function board(
  type: string,
  label: string,
  w: number,
  h: number,
  pins: Record<string, [number, number]>,
  opts: { sub?: string; accent?: string } = {}
): PartDef {
  const accent = opts.accent || '#3a4a78'
  return {
    type,
    label,
    family: 'tinyStudio',
    sub: opts.sub,
    accent,
    builtin: true,
    views: { breadboard: { svg: boardSvg(label, opts.sub, w, h, accent), w, h, pins } }
  }
}

const BUILTIN_PARTS: PartDef[] = [
  board(
    'tinycore',
    'tinyCore',
    150,
    150,
    {
      '3V3': [8, 70],
      GND: [8, 96],
      SIG: [142, 58],
      D3: [142, 78],
      D4: [142, 98],
      D5: [142, 118],
      D9: [74, 142]
    },
    { sub: 'ESP32-S3', accent: 'var(--cyan)' }
  ),
  board(
    'tinyglow',
    'tinyGlow',
    104,
    104,
    { VCC: [6, 40], GND: [6, 64], DIN: [98, 52] },
    { accent: 'var(--pink)' }
  ),
  board('tinyproto', 'tinyProto', 120, 100, {
    '+': [6, 30],
    '-': [6, 54],
    A: [114, 30],
    B: [114, 54]
  }),
  board('tinydisplay', 'tinyDisplay', 120, 100, {
    VCC: [6, 24],
    GND: [6, 48],
    SDA: [114, 24],
    SCL: [114, 48]
  }),
  board('tinysniff', 'tinySniff', 110, 100, {
    VCC: [6, 24],
    GND: [6, 48],
    SDA: [104, 24],
    SCL: [104, 48]
  })
]

// ── registry + lazy loading ──────────────────────────────────────────────────

// Lazy per-part loading. Each part is a flat file under assets/parts/ (Vite's
// dynamic-import variables only support a single path segment, so the family
// grouping lives in the manifest, not in directories). The ".json" extension
// stays in the static part of the template so Vite can analyze the glob.
const rawManifest = (manifestJson as { parts?: PartMeta[] }).parts || []
const loaderByType: Record<string, () => Promise<{ default: PartDef }>> = {}
for (const m of rawManifest) {
  if (!m.file) continue
  const rel = m.file.replace(/\.json$/, '')
  loaderByType[m.type] = () => import(`../assets/parts/${rel}.json`)
}

const cache: Record<string, PartDef> = {}
for (const d of BUILTIN_PARTS) cache[d.type] = d

const builtinMeta: PartMeta[] = BUILTIN_PARTS.map((d) => ({
  type: d.type,
  label: d.label,
  family: d.family || 'tinyStudio',
  views: Object.keys(d.views) as ViewKind[],
  pins: Object.keys(Object.values(d.views)[0]?.pins || {}).length,
  icon: d.icon || Object.values(d.views)[0]?.svg,
  builtin: true
}))

/** Palette metadata: built-ins first, then the Fritzing catalogue. */
export const PART_MANIFEST: PartMeta[] = [...builtinMeta, ...rawManifest]

/** Manifest grouped by family for the components rail. */
export function partsByFamily(): { family: string; parts: PartMeta[] }[] {
  const groups = new Map<string, PartMeta[]>()
  for (const p of PART_MANIFEST) {
    if (!groups.has(p.family)) groups.set(p.family, [])
    groups.get(p.family)!.push(p)
  }
  return Array.from(groups, ([family, parts]) => ({ family, parts }))
}

/** Synchronous lookup — only returns parts already loaded (built-ins + cached). */
export function getPart(type: string): PartDef | undefined {
  return cache[type]
}

/** Load a part definition (from cache if present, else its JSON file). */
export async function loadPart(type: string): Promise<PartDef | undefined> {
  if (cache[type]) return cache[type]
  const loader = loaderByType[type]
  if (!loader) return undefined
  const mod = await loader()
  cache[type] = mod.default
  return mod.default
}

/** Ensure every given type is loaded; resolves once the cache is populated. */
export async function ensureParts(types: Iterable<string>): Promise<void> {
  await Promise.all(Array.from(new Set(types)).map((t) => loadPart(t).catch(() => undefined)))
}

/** Register a user-authored part (from the Parts Editor) into the live registry. */
export function registerPart(def: PartDef): void {
  cache[def.type] = def
  const existing = PART_MANIFEST.findIndex((m) => m.type === def.type)
  const meta: PartMeta = {
    type: def.type,
    label: def.label,
    family: def.family || 'Custom',
    views: Object.keys(def.views) as ViewKind[],
    pins: Object.keys(Object.values(def.views)[0]?.pins || {}).length,
    icon: def.icon || Object.values(def.views)[0]?.svg,
    builtin: def.builtin
  }
  if (existing >= 0) PART_MANIFEST[existing] = meta
  else PART_MANIFEST.push(meta)
}

/** Pick the best available view for a part, preferring the requested one. */
export function viewFor(def: PartDef, view: ViewKind): PartView | undefined {
  return def.views[view] || def.views.breadboard || def.views.schematic
}
