// GENERATED by scripts/sync-tinyparts.mjs; do not edit.
// A copy of the bundled packs from github.com/Mister-Industries/tinyparts.
// To change a part, edit it in tinyparts and run `npm run parts:sync`.
/* eslint-disable */

import f0 from "./packs/tinyboards/pack.json?raw"
import f1 from "./packs/tinyboards/parts/tinycore/icon.svg?raw"
import f2 from "./packs/tinyboards/parts/tinycore/part.json?raw"
import f3 from "./packs/tinyboards/parts/tinydisplay/icon.svg?raw"
import f4 from "./packs/tinyboards/parts/tinydisplay/part.json?raw"
import f5 from "./packs/tinyboards/parts/tinyglow/icon.svg?raw"
import f6 from "./packs/tinyboards/parts/tinyglow/part.json?raw"
import f7 from "./packs/tinyboards/parts/tinyproto/icon.svg?raw"
import f8 from "./packs/tinyboards/parts/tinyproto/part.json?raw"
import f9 from "./packs/tinyboards/parts/tinysniff/icon.svg?raw"
import f10 from "./packs/tinyboards/parts/tinysniff/part.json?raw"
import f11 from "./packs/tinyboards/parts/tinyspeak/icon.svg?raw"
import f12 from "./packs/tinyboards/parts/tinyspeak/part.json?raw"
import f13 from "./packs/core/pack.json?raw"
import f14 from "./packs/core/parts/7segment-100-cat/icon.svg?raw"
import f15 from "./packs/core/parts/7segment-100-cat/part.json?raw"
import f16 from "./packs/core/parts/battery-aa/icon.svg?raw"
import f17 from "./packs/core/parts/battery-aa/part.json?raw"
import f18 from "./packs/core/parts/buzzer-v15/breadboard.svg?raw"
import f19 from "./packs/core/parts/buzzer-v15/part.json?raw"
import f20 from "./packs/core/parts/capacitor-ceramic-100mil/icon.svg?raw"
import f21 from "./packs/core/parts/capacitor-ceramic-100mil/part.json?raw"
import f22 from "./packs/core/parts/capacitor-ceramic-200mil/icon.svg?raw"
import f23 from "./packs/core/parts/capacitor-ceramic-200mil/part.json?raw"
import f24 from "./packs/core/parts/capacitor-electrolytic-medium/icon.svg?raw"
import f25 from "./packs/core/parts/capacitor-electrolytic-medium/part.json?raw"
import f26 from "./packs/core/parts/diode-1n4001-300mil/icon.svg?raw"
import f27 from "./packs/core/parts/diode-1n4001-300mil/part.json?raw"
import f28 from "./packs/core/parts/diode-zener-0-5w-3-6v-300mil/icon.svg?raw"
import f29 from "./packs/core/parts/diode-zener-0-5w-3-6v-300mil/part.json?raw"
import f30 from "./packs/core/parts/ir-receiver-v14/breadboard.svg?raw"
import f31 from "./packs/core/parts/ir-receiver-v14/part.json?raw"
import f32 from "./packs/core/parts/ldr-photocell-300mil-v5/icon.svg?raw"
import f33 from "./packs/core/parts/ldr-photocell-300mil-v5/part.json?raw"
import f34 from "./packs/core/parts/led-generic-3mm/icon.svg?raw"
import f35 from "./packs/core/parts/led-generic-3mm/part.json?raw"
import f36 from "./packs/core/parts/led-generic-5mm/icon.svg?raw"
import f37 from "./packs/core/parts/led-generic-5mm/part.json?raw"
import f38 from "./packs/core/parts/piezo-sensor/icon.svg?raw"
import f39 from "./packs/core/parts/piezo-sensor/part.json?raw"
import f40 from "./packs/core/parts/potentiometer-rotary-16mm-5/icon.svg?raw"
import f41 from "./packs/core/parts/potentiometer-rotary-16mm-5/part.json?raw"
import f42 from "./packs/core/parts/potentiometer-trimmer-6mm-5/icon.svg?raw"
import f43 from "./packs/core/parts/potentiometer-trimmer-6mm-5/part.json?raw"
import f44 from "./packs/core/parts/pushbutton/icon.svg?raw"
import f45 from "./packs/core/parts/pushbutton/part.json?raw"
import f46 from "./packs/core/parts/reedswitch-500mil/icon.svg?raw"
import f47 from "./packs/core/parts/reedswitch-500mil/part.json?raw"
import f48 from "./packs/core/parts/resistor/icon.svg?raw"
import f49 from "./packs/core/parts/resistor/part.json?raw"
import f50 from "./packs/core/parts/servo/icon.svg?raw"
import f51 from "./packs/core/parts/servo/part.json?raw"
import f52 from "./packs/core/parts/smd-inductor-0805/icon.svg?raw"
import f53 from "./packs/core/parts/smd-inductor-0805/part.json?raw"
import f54 from "./packs/core/parts/sparkfun-discretesemi-mosfet-nchannel-pth/breadboard.svg?raw"
import f55 from "./packs/core/parts/sparkfun-discretesemi-mosfet-nchannel-pth/part.json?raw"
import f56 from "./packs/core/parts/sparkfun-passives-fuse-x20mm/breadboard.svg?raw"
import f57 from "./packs/core/parts/sparkfun-passives-fuse-x20mm/part.json?raw"
import f58 from "./packs/core/parts/sparkfun-sensors-mic-electret-smd/icon.svg?raw"
import f59 from "./packs/core/parts/sparkfun-sensors-mic-electret-smd/part.json?raw"
import f60 from "./packs/core/parts/switch-spst/breadboard.svg?raw"
import f61 from "./packs/core/parts/switch-spst/part.json?raw"
import f62 from "./packs/core/parts/te-relay/icon.svg?raw"
import f63 from "./packs/core/parts/te-relay/part.json?raw"
import f64 from "./packs/core/parts/thermistor-300mil/icon.svg?raw"
import f65 from "./packs/core/parts/thermistor-300mil/part.json?raw"
import f66 from "./packs/core/parts/transistor-signal-npn-to92-ebc/icon.svg?raw"
import f67 from "./packs/core/parts/transistor-signal-npn-to92-ebc/part.json?raw"
import f68 from "./packs/core/parts/transistor-signal-pnp-to92-ebc/icon.svg?raw"
import f69 from "./packs/core/parts/transistor-signal-pnp-to92-ebc/part.json?raw"
import f70 from "./packs/core/parts/voltage-regulator-7805/icon.svg?raw"
import f71 from "./packs/core/parts/voltage-regulator-7805/part.json?raw"

export interface SnapshotPack {
  id: string
  /** pack-relative path → git blob sha */
  files: Record<string, string>
}

export interface TinypartsSnapshot {
  /** GitHub owner/repo the packs came from */
  repo: string
  /** tinyparts HEAD when synced */
  commit: string
  /** true if the checkout had uncommitted changes in these packs */
  dirty: boolean
  packs: SnapshotPack[]
}

export const SNAPSHOT: TinypartsSnapshot = {
  "repo": "Mister-Industries/tinyparts",
  "commit": "d952101940bbeddc7cecadb549f54a34198be38c",
  "dirty": false,
  "packs": [
    {
      "id": "tinyboards",
      "files": {
        "pack.json": "326f843ade0dbd0bbee0b8319fe5cf7525331653",
        "parts/tinycore/breadboard.svg": "1779cf14d778fc1a9344ff7a79fd2c4ecc3c968f",
        "parts/tinycore/icon.svg": "334dfafa8d2954026c2448486a7aafeadac28e51",
        "parts/tinycore/part.json": "4168f74b75e81176d4d09a3bbc36cc0782e5322b",
        "parts/tinydisplay/breadboard.svg": "411211170cdd786ed66bf34ce09190a928661c5c",
        "parts/tinydisplay/icon.svg": "5c090fc0fe43c4250087c233f68feab4a616c1e9",
        "parts/tinydisplay/part.json": "2fc0bf7f33de43eb5d2069fade89b327a0414a1c",
        "parts/tinyglow/breadboard.svg": "cec2d1227f82df2bd3e0e376d509fa1bbe7230c9",
        "parts/tinyglow/icon.svg": "f30714fbc20507685d08595d35282577a228d845",
        "parts/tinyglow/part.json": "b75e1713e62cf730b0806b5392b7a5c6edd0d7b9",
        "parts/tinyproto/breadboard.svg": "3772b77d543b004105083515e9de76bb49dc0b9c",
        "parts/tinyproto/icon.svg": "3772b77d543b004105083515e9de76bb49dc0b9c",
        "parts/tinyproto/part.json": "5f8707d4a2f3d2344443b7638eb0863104615af9",
        "parts/tinysniff/breadboard.svg": "1f2919cefb222c0db630bcf4db8db192e457ae0e",
        "parts/tinysniff/icon.svg": "92f9363ecb9755bca44ad5bc3eed9212202c39e6",
        "parts/tinysniff/part.json": "8ceeef62e1b245133d19a76694fd24deaf0810ce",
        "parts/tinyspeak/breadboard.svg": "e9dcf76268ab87f0f3f7b7e9a601b62ab8c69221",
        "parts/tinyspeak/icon.svg": "e9dcf76268ab87f0f3f7b7e9a601b62ab8c69221",
        "parts/tinyspeak/part.json": "8a33d2ae8283ecd4de172154f79bc673d0a36e54"
      }
    },
    {
      "id": "core",
      "files": {
        "pack.json": "b06a82ce18ab4b3615873fbd04273c763916c997",
        "parts/7segment-100-cat/breadboard.svg": "549167978aff3849ac58e839a9cace3a5b1b5b9a",
        "parts/7segment-100-cat/icon.svg": "1e49653dea165e4387fc708c6f1f09584d42d4ff",
        "parts/7segment-100-cat/part.json": "e9b66edd52a8255306ac0b62d3514914adc51eef",
        "parts/7segment-100-cat/schematic.svg": "f19d3385a7482fafc874f1be4ead4b94ddc565ab",
        "parts/battery-aa/breadboard.svg": "22342cfb0e45063ed77760cac2ed69f18c2c2b1b",
        "parts/battery-aa/icon.svg": "56c623ef0d2acddb02ace41ec98866d618632da9",
        "parts/battery-aa/part.json": "6db446ada25fdce4df10c7156fc875c345e02904",
        "parts/battery-aa/schematic.svg": "25b94ba93d9371332bb59041889e5879af675fe0",
        "parts/buzzer-v15/breadboard.svg": "2812ed474e704a2182894c0f81d596ea77490785",
        "parts/buzzer-v15/part.json": "44d2567d8399861a40706368177b5b3b0b07751c",
        "parts/buzzer-v15/schematic.svg": "e5b51c5023a3e02afb23c41f53e700a4e103c248",
        "parts/capacitor-ceramic-100mil/breadboard.svg": "02062b2f9ff00e9eeeed6de9048dd45e21297946",
        "parts/capacitor-ceramic-100mil/icon.svg": "e7be3c610c13009b7279b9b518880507a1c7c44c",
        "parts/capacitor-ceramic-100mil/part.json": "b7261f798e9cbdbe4d800158b57c3ded507135fc",
        "parts/capacitor-ceramic-100mil/schematic.svg": "d3c4d03fad2b4db0e7346d279f1360f3f4aa0688",
        "parts/capacitor-ceramic-200mil/breadboard.svg": "02062b2f9ff00e9eeeed6de9048dd45e21297946",
        "parts/capacitor-ceramic-200mil/icon.svg": "e7be3c610c13009b7279b9b518880507a1c7c44c",
        "parts/capacitor-ceramic-200mil/part.json": "f5e85ba21b4968abac2a1506520956e8e6664bcb",
        "parts/capacitor-ceramic-200mil/schematic.svg": "d3c4d03fad2b4db0e7346d279f1360f3f4aa0688",
        "parts/capacitor-electrolytic-medium/breadboard.svg": "ea972cac6303eda46ff71251a60c0f088b1f3a92",
        "parts/capacitor-electrolytic-medium/icon.svg": "169078426d45dc367ac32117c2e8cd52a09f6b80",
        "parts/capacitor-electrolytic-medium/part.json": "635c972a1257ac5ec7d89d1eb39958dbd67933ea",
        "parts/capacitor-electrolytic-medium/schematic.svg": "e41974ea66b785eaf71e1a370dc5f961e32a411c",
        "parts/diode-1n4001-300mil/breadboard.svg": "51ec146c16817c12b77822408e6ce305d2b892fc",
        "parts/diode-1n4001-300mil/icon.svg": "99919136a3a31140a0859dca98cfe2da87997a6d",
        "parts/diode-1n4001-300mil/part.json": "814f19c8345f11443be57c5595a6c3b1e99ba290",
        "parts/diode-1n4001-300mil/schematic.svg": "80c4d6c13d7797784a3642bcc5eeab70913aae88",
        "parts/diode-zener-0-5w-3-6v-300mil/breadboard.svg": "51ec146c16817c12b77822408e6ce305d2b892fc",
        "parts/diode-zener-0-5w-3-6v-300mil/icon.svg": "99919136a3a31140a0859dca98cfe2da87997a6d",
        "parts/diode-zener-0-5w-3-6v-300mil/part.json": "5762173d65ffd26e7eff918436d9d88c700ca2d7",
        "parts/diode-zener-0-5w-3-6v-300mil/schematic.svg": "09811f92bec361481c131a8f61c67da1403e994a",
        "parts/ir-receiver-v14/breadboard.svg": "de3ac1dc191c090f1a9981ea4581d3a9ee8cbc44",
        "parts/ir-receiver-v14/part.json": "ac23a62480de5de506790ecd2596b6490bd2a5d5",
        "parts/ir-receiver-v14/schematic.svg": "4ebaef490ada9008220e4b53ed2e8434aed8200f",
        "parts/ldr-photocell-300mil-v5/breadboard.svg": "284910b8672ac440de9d4e7691480834f2033ffa",
        "parts/ldr-photocell-300mil-v5/icon.svg": "27a0dc98adc0b63497314387f4e693b0da81cd3d",
        "parts/ldr-photocell-300mil-v5/part.json": "18ef5a1a2f645719d1dee7e329e5614fc46ae648",
        "parts/ldr-photocell-300mil-v5/schematic.svg": "6660b5610395757ccf14a36dc190d800ff4013ba",
        "parts/led-generic-3mm/breadboard.svg": "dc70fef7340cd3ab0450755a6d67eb194919c378",
        "parts/led-generic-3mm/icon.svg": "c44612f7d0be61ab81a7afac049679b49f397a83",
        "parts/led-generic-3mm/part.json": "b747876a98de5aaf9a1a706abad2c40942825007",
        "parts/led-generic-3mm/schematic.svg": "2a877c8184018980eea99b1e2d414097798b03b6",
        "parts/led-generic-5mm/breadboard.svg": "5cb64cd51cc0309085f100e21434850f116f173f",
        "parts/led-generic-5mm/icon.svg": "c44612f7d0be61ab81a7afac049679b49f397a83",
        "parts/led-generic-5mm/part.json": "bc7557fa9cb28e0069b27f478972b583f6857f77",
        "parts/led-generic-5mm/schematic.svg": "2a877c8184018980eea99b1e2d414097798b03b6",
        "parts/piezo-sensor/breadboard.svg": "7d128d79612d4f0b50a9773ff13cbbc79d088dea",
        "parts/piezo-sensor/icon.svg": "ceba2eb508701d6070c4d385f7659a2db73f719a",
        "parts/piezo-sensor/part.json": "c5e871263b4dbce52ea3563abcf98ff092d5b2bb",
        "parts/piezo-sensor/schematic.svg": "e0c2fc9588750fdd57caaeed41654af0cf36e2e6",
        "parts/potentiometer-rotary-16mm-5/breadboard.svg": "f5dbc44ccb248abd19d61a4e84599db934dfe8f2",
        "parts/potentiometer-rotary-16mm-5/icon.svg": "5c7a529bcacff30ca84d03d53d4cff77a9192a60",
        "parts/potentiometer-rotary-16mm-5/part.json": "adbf1410be85969943861260886a1b4b568b58f6",
        "parts/potentiometer-rotary-16mm-5/schematic.svg": "9004e013768755bce1bb6a5ef6cf09d823cab9a9",
        "parts/potentiometer-trimmer-6mm-5/breadboard.svg": "2ad4b3b88117fc96ea77c057229eddd5a1140b87",
        "parts/potentiometer-trimmer-6mm-5/icon.svg": "05597dfffb400bdb2d0d10d8a321bdce0edc655b",
        "parts/potentiometer-trimmer-6mm-5/part.json": "aff61cc68384f9d0eb14788ad37f073e6c75b935",
        "parts/potentiometer-trimmer-6mm-5/schematic.svg": "9004e013768755bce1bb6a5ef6cf09d823cab9a9",
        "parts/pushbutton/breadboard.svg": "542c3f0b6ba67104271630e77577380283255736",
        "parts/pushbutton/icon.svg": "4fe6b429af4ff654eb299b8b33c72f497254f757",
        "parts/pushbutton/part.json": "8fdd248cdbb31646db904cca3f53330fc362fb22",
        "parts/pushbutton/schematic.svg": "78ca75365d07c68223fc618b2fe16128bb123f33",
        "parts/reedswitch-500mil/breadboard.svg": "b406d2c3ec035017488fce5e5328e2c12c3b0f58",
        "parts/reedswitch-500mil/icon.svg": "70bcc955c5874458f0bdb924923fc3a29ab651b9",
        "parts/reedswitch-500mil/part.json": "cc2f3dc9bf2a39b826e76ce84e038461fc1105d7",
        "parts/reedswitch-500mil/schematic.svg": "bc98dc6b6e0affadb4921107327c2471df8438dc",
        "parts/resistor/breadboard.svg": "0b736e0f7918684500fde5cebbe7fe7329e59648",
        "parts/resistor/icon.svg": "d7daecb5944342363d205b756c64b9a712ce4f6d",
        "parts/resistor/part.json": "b2c5cbc7e163f05f02db8f401227d0d6945211cc",
        "parts/resistor/schematic.svg": "a65b548dc01d66e92f09eca6d40e1d8cd0850726",
        "parts/servo/breadboard.svg": "2e576b33d7f6f6f1ec8ee324443d119e91084df6",
        "parts/servo/icon.svg": "51479534c0f8fdcd4d88149c41777d28c07a411d",
        "parts/servo/part.json": "bc9154bc15186020d9d8190983a8dfd8aeccd5c2",
        "parts/servo/schematic.svg": "7a861f3ac394ff6bfb898bb5c6fc4b5acd20fa64",
        "parts/smd-inductor-0805/breadboard.svg": "b29f48f7034ab4fd98399fdc03deab2d39398f02",
        "parts/smd-inductor-0805/icon.svg": "7221c0a29eaae9b357378e4d6c8f4980c65f60b7",
        "parts/smd-inductor-0805/part.json": "5bb4d3653ca1ac06a85d97fceb2998b4b9d52cd8",
        "parts/smd-inductor-0805/schematic.svg": "7d4d33d90136afe4f440dc2e3644c80404de4e32",
        "parts/sparkfun-discretesemi-mosfet-nchannel-pth/breadboard.svg": "df12961a1728fc4dc8f3b4bbe6cec9911c869fe5",
        "parts/sparkfun-discretesemi-mosfet-nchannel-pth/part.json": "4af45bc914333fd252d27ff84bbd04caae278eeb",
        "parts/sparkfun-discretesemi-mosfet-nchannel-pth/schematic.svg": "7c3552169c311b0b31f6790affca783053446b76",
        "parts/sparkfun-passives-fuse-x20mm/breadboard.svg": "33b62863e197f81109a6046583bcc66f7713513f",
        "parts/sparkfun-passives-fuse-x20mm/part.json": "a3b5db0655083f16f60ff96e2e333857073ffdfc",
        "parts/sparkfun-passives-fuse-x20mm/schematic.svg": "44486fa7609d8cb3dec2d6b377259ac20668c9c5",
        "parts/sparkfun-sensors-mic-electret-smd/breadboard.svg": "1b447742b02fcbc735ac85e0a0edf328d5d5e257",
        "parts/sparkfun-sensors-mic-electret-smd/icon.svg": "659febcd8df0c34bee22ca5defd021c2aac08c0e",
        "parts/sparkfun-sensors-mic-electret-smd/part.json": "428ea09ae870a8c1198362b8adc218fcf450aac1",
        "parts/sparkfun-sensors-mic-electret-smd/schematic.svg": "f354a4ebdfdb99bdcc2cee8c22fe2664d1d0392e",
        "parts/switch-spst/breadboard.svg": "65b55040aa3fa0142449296e9f8dd43298c035ce",
        "parts/switch-spst/part.json": "fa69bfca28dbafa33cfa8309541b9b644874e25e",
        "parts/te-relay/breadboard.svg": "8cd7f4358b8345e2307e87e1e83e0c4a188188ee",
        "parts/te-relay/icon.svg": "97ac95d7ccc2d2fca31ce077299c3a74bf310f23",
        "parts/te-relay/part.json": "e86b2da7360d240d7d6a0e3b5b804867cc49f884",
        "parts/te-relay/schematic.svg": "2f39b0b17253dedb02b0699927aa71741a13749e",
        "parts/thermistor-300mil/breadboard.svg": "12cf0b00d4fc40c48852aec520b4498a98a06854",
        "parts/thermistor-300mil/icon.svg": "fe22ce0e02f5d69c563f30cea162394913c7e056",
        "parts/thermistor-300mil/part.json": "4e663f7f163c37c2fba93831d94b00bd0541deed",
        "parts/thermistor-300mil/schematic.svg": "29df2e7f6e09dc4c0087b60b9cbd0bdff36308de",
        "parts/transistor-signal-npn-to92-ebc/breadboard.svg": "b71e6d3965cb6fd3bfad97ffc3f06a6c8a670096",
        "parts/transistor-signal-npn-to92-ebc/icon.svg": "5fc7ba3e62e7b759477519ec2a631b8b7577c23e",
        "parts/transistor-signal-npn-to92-ebc/part.json": "85565d68a7815ce2dca0ff7c11ae0b1b66eeaea4",
        "parts/transistor-signal-npn-to92-ebc/schematic.svg": "7e3e757e9f0646582f816864bbe21d258857104e",
        "parts/transistor-signal-pnp-to92-ebc/breadboard.svg": "df12961a1728fc4dc8f3b4bbe6cec9911c869fe5",
        "parts/transistor-signal-pnp-to92-ebc/icon.svg": "36f80c8bed181c4ee02de7cec866479ab4c2594c",
        "parts/transistor-signal-pnp-to92-ebc/part.json": "8327cd9b44588aa2fc98d82025676a684ad5ed7a",
        "parts/transistor-signal-pnp-to92-ebc/schematic.svg": "b993b93762ee30164a6c5a83dd9171f8a146c832",
        "parts/voltage-regulator-7805/breadboard.svg": "3fa48ac7a68dcfaed5e784ef15427dc8cd39bede",
        "parts/voltage-regulator-7805/icon.svg": "b2dcab03a257aa83aa49e87d0b0a3faa2f4c22d9",
        "parts/voltage-regulator-7805/part.json": "f20dc8dd96688a8c6caf5bf2bfd337622ebe66d8",
        "parts/voltage-regulator-7805/schematic.svg": "826c96941f90e26d931c27d63f3a93f9c2953f06"
      }
    }
  ]
}

/** repo-relative path → file text (part.json, pack.json and palette icons) */
export const EAGER: Record<string, string> = {
  "packs/tinyboards/pack.json": f0,
  "packs/tinyboards/parts/tinycore/icon.svg": f1,
  "packs/tinyboards/parts/tinycore/part.json": f2,
  "packs/tinyboards/parts/tinydisplay/icon.svg": f3,
  "packs/tinyboards/parts/tinydisplay/part.json": f4,
  "packs/tinyboards/parts/tinyglow/icon.svg": f5,
  "packs/tinyboards/parts/tinyglow/part.json": f6,
  "packs/tinyboards/parts/tinyproto/icon.svg": f7,
  "packs/tinyboards/parts/tinyproto/part.json": f8,
  "packs/tinyboards/parts/tinysniff/icon.svg": f9,
  "packs/tinyboards/parts/tinysniff/part.json": f10,
  "packs/tinyboards/parts/tinyspeak/icon.svg": f11,
  "packs/tinyboards/parts/tinyspeak/part.json": f12,
  "packs/core/pack.json": f13,
  "packs/core/parts/7segment-100-cat/icon.svg": f14,
  "packs/core/parts/7segment-100-cat/part.json": f15,
  "packs/core/parts/battery-aa/icon.svg": f16,
  "packs/core/parts/battery-aa/part.json": f17,
  "packs/core/parts/buzzer-v15/breadboard.svg": f18,
  "packs/core/parts/buzzer-v15/part.json": f19,
  "packs/core/parts/capacitor-ceramic-100mil/icon.svg": f20,
  "packs/core/parts/capacitor-ceramic-100mil/part.json": f21,
  "packs/core/parts/capacitor-ceramic-200mil/icon.svg": f22,
  "packs/core/parts/capacitor-ceramic-200mil/part.json": f23,
  "packs/core/parts/capacitor-electrolytic-medium/icon.svg": f24,
  "packs/core/parts/capacitor-electrolytic-medium/part.json": f25,
  "packs/core/parts/diode-1n4001-300mil/icon.svg": f26,
  "packs/core/parts/diode-1n4001-300mil/part.json": f27,
  "packs/core/parts/diode-zener-0-5w-3-6v-300mil/icon.svg": f28,
  "packs/core/parts/diode-zener-0-5w-3-6v-300mil/part.json": f29,
  "packs/core/parts/ir-receiver-v14/breadboard.svg": f30,
  "packs/core/parts/ir-receiver-v14/part.json": f31,
  "packs/core/parts/ldr-photocell-300mil-v5/icon.svg": f32,
  "packs/core/parts/ldr-photocell-300mil-v5/part.json": f33,
  "packs/core/parts/led-generic-3mm/icon.svg": f34,
  "packs/core/parts/led-generic-3mm/part.json": f35,
  "packs/core/parts/led-generic-5mm/icon.svg": f36,
  "packs/core/parts/led-generic-5mm/part.json": f37,
  "packs/core/parts/piezo-sensor/icon.svg": f38,
  "packs/core/parts/piezo-sensor/part.json": f39,
  "packs/core/parts/potentiometer-rotary-16mm-5/icon.svg": f40,
  "packs/core/parts/potentiometer-rotary-16mm-5/part.json": f41,
  "packs/core/parts/potentiometer-trimmer-6mm-5/icon.svg": f42,
  "packs/core/parts/potentiometer-trimmer-6mm-5/part.json": f43,
  "packs/core/parts/pushbutton/icon.svg": f44,
  "packs/core/parts/pushbutton/part.json": f45,
  "packs/core/parts/reedswitch-500mil/icon.svg": f46,
  "packs/core/parts/reedswitch-500mil/part.json": f47,
  "packs/core/parts/resistor/icon.svg": f48,
  "packs/core/parts/resistor/part.json": f49,
  "packs/core/parts/servo/icon.svg": f50,
  "packs/core/parts/servo/part.json": f51,
  "packs/core/parts/smd-inductor-0805/icon.svg": f52,
  "packs/core/parts/smd-inductor-0805/part.json": f53,
  "packs/core/parts/sparkfun-discretesemi-mosfet-nchannel-pth/breadboard.svg": f54,
  "packs/core/parts/sparkfun-discretesemi-mosfet-nchannel-pth/part.json": f55,
  "packs/core/parts/sparkfun-passives-fuse-x20mm/breadboard.svg": f56,
  "packs/core/parts/sparkfun-passives-fuse-x20mm/part.json": f57,
  "packs/core/parts/sparkfun-sensors-mic-electret-smd/icon.svg": f58,
  "packs/core/parts/sparkfun-sensors-mic-electret-smd/part.json": f59,
  "packs/core/parts/switch-spst/breadboard.svg": f60,
  "packs/core/parts/switch-spst/part.json": f61,
  "packs/core/parts/te-relay/icon.svg": f62,
  "packs/core/parts/te-relay/part.json": f63,
  "packs/core/parts/thermistor-300mil/icon.svg": f64,
  "packs/core/parts/thermistor-300mil/part.json": f65,
  "packs/core/parts/transistor-signal-npn-to92-ebc/icon.svg": f66,
  "packs/core/parts/transistor-signal-npn-to92-ebc/part.json": f67,
  "packs/core/parts/transistor-signal-pnp-to92-ebc/icon.svg": f68,
  "packs/core/parts/transistor-signal-pnp-to92-ebc/part.json": f69,
  "packs/core/parts/voltage-regulator-7805/icon.svg": f70,
  "packs/core/parts/voltage-regulator-7805/part.json": f71,
}

/** repo-relative path → lazy loader for everything else */
export const LAZY: Record<string, () => Promise<string>> = {
  "packs/tinyboards/parts/tinycore/breadboard.svg": () => import("./packs/tinyboards/parts/tinycore/breadboard.svg?raw").then((m) => m.default),
  "packs/tinyboards/parts/tinydisplay/breadboard.svg": () => import("./packs/tinyboards/parts/tinydisplay/breadboard.svg?raw").then((m) => m.default),
  "packs/tinyboards/parts/tinyglow/breadboard.svg": () => import("./packs/tinyboards/parts/tinyglow/breadboard.svg?raw").then((m) => m.default),
  "packs/tinyboards/parts/tinyproto/breadboard.svg": () => import("./packs/tinyboards/parts/tinyproto/breadboard.svg?raw").then((m) => m.default),
  "packs/tinyboards/parts/tinysniff/breadboard.svg": () => import("./packs/tinyboards/parts/tinysniff/breadboard.svg?raw").then((m) => m.default),
  "packs/tinyboards/parts/tinyspeak/breadboard.svg": () => import("./packs/tinyboards/parts/tinyspeak/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/7segment-100-cat/breadboard.svg": () => import("./packs/core/parts/7segment-100-cat/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/7segment-100-cat/schematic.svg": () => import("./packs/core/parts/7segment-100-cat/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/battery-aa/breadboard.svg": () => import("./packs/core/parts/battery-aa/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/battery-aa/schematic.svg": () => import("./packs/core/parts/battery-aa/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/buzzer-v15/schematic.svg": () => import("./packs/core/parts/buzzer-v15/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/capacitor-ceramic-100mil/breadboard.svg": () => import("./packs/core/parts/capacitor-ceramic-100mil/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/capacitor-ceramic-100mil/schematic.svg": () => import("./packs/core/parts/capacitor-ceramic-100mil/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/capacitor-ceramic-200mil/breadboard.svg": () => import("./packs/core/parts/capacitor-ceramic-200mil/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/capacitor-ceramic-200mil/schematic.svg": () => import("./packs/core/parts/capacitor-ceramic-200mil/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/capacitor-electrolytic-medium/breadboard.svg": () => import("./packs/core/parts/capacitor-electrolytic-medium/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/capacitor-electrolytic-medium/schematic.svg": () => import("./packs/core/parts/capacitor-electrolytic-medium/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/diode-1n4001-300mil/breadboard.svg": () => import("./packs/core/parts/diode-1n4001-300mil/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/diode-1n4001-300mil/schematic.svg": () => import("./packs/core/parts/diode-1n4001-300mil/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/diode-zener-0-5w-3-6v-300mil/breadboard.svg": () => import("./packs/core/parts/diode-zener-0-5w-3-6v-300mil/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/diode-zener-0-5w-3-6v-300mil/schematic.svg": () => import("./packs/core/parts/diode-zener-0-5w-3-6v-300mil/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/ir-receiver-v14/schematic.svg": () => import("./packs/core/parts/ir-receiver-v14/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/ldr-photocell-300mil-v5/breadboard.svg": () => import("./packs/core/parts/ldr-photocell-300mil-v5/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/ldr-photocell-300mil-v5/schematic.svg": () => import("./packs/core/parts/ldr-photocell-300mil-v5/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/led-generic-3mm/breadboard.svg": () => import("./packs/core/parts/led-generic-3mm/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/led-generic-3mm/schematic.svg": () => import("./packs/core/parts/led-generic-3mm/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/led-generic-5mm/breadboard.svg": () => import("./packs/core/parts/led-generic-5mm/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/led-generic-5mm/schematic.svg": () => import("./packs/core/parts/led-generic-5mm/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/piezo-sensor/breadboard.svg": () => import("./packs/core/parts/piezo-sensor/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/piezo-sensor/schematic.svg": () => import("./packs/core/parts/piezo-sensor/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/potentiometer-rotary-16mm-5/breadboard.svg": () => import("./packs/core/parts/potentiometer-rotary-16mm-5/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/potentiometer-rotary-16mm-5/schematic.svg": () => import("./packs/core/parts/potentiometer-rotary-16mm-5/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/potentiometer-trimmer-6mm-5/breadboard.svg": () => import("./packs/core/parts/potentiometer-trimmer-6mm-5/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/potentiometer-trimmer-6mm-5/schematic.svg": () => import("./packs/core/parts/potentiometer-trimmer-6mm-5/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/pushbutton/breadboard.svg": () => import("./packs/core/parts/pushbutton/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/pushbutton/schematic.svg": () => import("./packs/core/parts/pushbutton/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/reedswitch-500mil/breadboard.svg": () => import("./packs/core/parts/reedswitch-500mil/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/reedswitch-500mil/schematic.svg": () => import("./packs/core/parts/reedswitch-500mil/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/resistor/breadboard.svg": () => import("./packs/core/parts/resistor/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/resistor/schematic.svg": () => import("./packs/core/parts/resistor/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/servo/breadboard.svg": () => import("./packs/core/parts/servo/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/servo/schematic.svg": () => import("./packs/core/parts/servo/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/smd-inductor-0805/breadboard.svg": () => import("./packs/core/parts/smd-inductor-0805/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/smd-inductor-0805/schematic.svg": () => import("./packs/core/parts/smd-inductor-0805/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/sparkfun-discretesemi-mosfet-nchannel-pth/schematic.svg": () => import("./packs/core/parts/sparkfun-discretesemi-mosfet-nchannel-pth/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/sparkfun-passives-fuse-x20mm/schematic.svg": () => import("./packs/core/parts/sparkfun-passives-fuse-x20mm/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/sparkfun-sensors-mic-electret-smd/breadboard.svg": () => import("./packs/core/parts/sparkfun-sensors-mic-electret-smd/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/sparkfun-sensors-mic-electret-smd/schematic.svg": () => import("./packs/core/parts/sparkfun-sensors-mic-electret-smd/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/te-relay/breadboard.svg": () => import("./packs/core/parts/te-relay/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/te-relay/schematic.svg": () => import("./packs/core/parts/te-relay/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/thermistor-300mil/breadboard.svg": () => import("./packs/core/parts/thermistor-300mil/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/thermistor-300mil/schematic.svg": () => import("./packs/core/parts/thermistor-300mil/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/transistor-signal-npn-to92-ebc/breadboard.svg": () => import("./packs/core/parts/transistor-signal-npn-to92-ebc/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/transistor-signal-npn-to92-ebc/schematic.svg": () => import("./packs/core/parts/transistor-signal-npn-to92-ebc/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/transistor-signal-pnp-to92-ebc/breadboard.svg": () => import("./packs/core/parts/transistor-signal-pnp-to92-ebc/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/transistor-signal-pnp-to92-ebc/schematic.svg": () => import("./packs/core/parts/transistor-signal-pnp-to92-ebc/schematic.svg?raw").then((m) => m.default),
  "packs/core/parts/voltage-regulator-7805/breadboard.svg": () => import("./packs/core/parts/voltage-regulator-7805/breadboard.svg?raw").then((m) => m.default),
  "packs/core/parts/voltage-regulator-7805/schematic.svg": () => import("./packs/core/parts/voltage-regulator-7805/schematic.svg?raw").then((m) => m.default),
}
